# Logging
LogFile /var/log/clamav/clamd.log
LogTime yes

# We need two of these and I have no idea why:
LocalSocket /tmp/clamd.sock
LocalSocket /tmp/clamd.sock

# The TCP socket port, used by other containers and the web app
TCPSocket 3310

# Run as another user (clamd must be started by root to make this option working).
# We use a user here because of how the docker container works.
# Default: no
User clamav

# Clamd uses FTP-like protocol to receive data from remote clients.
# If you are using clamav-milter to balance load between remote clamd daemons on firewall servers you may need to tune the Stream* options.
# This option allows you to specify the upper limit for data size that will be transferred to remote daemon when scanning a single file.
# It should match your MTA's limit for a maximum attachment size.
# Default: 10M
StreamMaxLength 128M

# Sets the maximum amount of data to be scanned for each input file.
# Archives and other containers are recursively extracted and scanned up to this value.
# Warning: disabling this limit or setting it too high may result in severe damage to the system.
# Default: 100M
MaxScanSize 512M

# Files larger than this limit won't be scanned.
# Affects the input file itself as well as files contained inside it
# (when the input file is an archive, a document or some other kind of container).
# Warning: disabling this limit or setting it too high may result in severe damage to the system.
# Default: 25M
MaxFileSize

