<?php

/**
 * A list of spam words that should be filtered
 *
 * IMPORTANT: All these words need to be lowercase
 *
 * Disable Spellchecker: cSpell:disable
 */
return [
    '+25',
    '+27',
    '100% free',
    '100% satisfied',
    'abortion',
    'act now',
    'additional income',
    'amphetamine',
    'apply now',
    'as seen on',
    'bargain',
    'be your own boss',
    'become a member',
    'beneficiary',
    'big bucks',
    'billing',
    'bitcoin',
    'bulk email',
    'buy direct',
    'buy fake',
    'call now',
    'cancel at any time',
    'cannabis',
    'cards accepted',
    'cash bonus',
    'cents on the dollar',
    'certified',
    'check or money order',
    'clearance',
    'compare rates',
    'confidentiality',
    'congratulations',
    'consolidate debt',
    'credit card',
    'crypto',
    'dear friend',
    'direct email',
    'direct marketing',
    'double your cash',
    'double your income',
    'drivers license',
    'dubai',
    'earn extra cash',
    'earn money',
    'eliminate bad credit',
    'encrypter',
    'exclusive deal',
    'expect to earn',
    'extra cash',
    'extra income',
    'fake passport',
    'fast cash',
    'financial freedom',
    'free access',
    'free consultation',
    'free gift',
    'free hosting',
    'free info',
    'free investment',
    'free membership',
    'free money',
    'free preview',
    'free quote',
    'free trial',
    'full refund',
    'get it now',
    'get out of debt',
    'get paid',
    'get started now',
    'giveaway',
    'hidden charges',
    'https',
    'human growth hormone',
    'important information regarding',
    'in accordance with laws',
    'income',
    'increase sales',
    'increase traffic',
    'incredible deal',
    'information you requested',
    'internet marketing',
    'investment',
    'join millions',
    'lose weight',
    'lower rates',
    'lowest price',
    'luxury',
    'maestro',
    'marketing solution',
    'mass email',
    'medication',
    'meet singles',
    'message contains',
    'million dollars',
    'miracle',
    'mortgage rates',
    'multi-level marketing',
    'name brand',
    'new customers only',
    'no catch',
    'no credit check',
    'no fees',
    'no hidden costs',
    'no hidden fees',
    'no interest',
    'no investment',
    'no obligation',
    'no purchase necessary',
    'no questions asked',
    'no strings attached',
    'not junk',
    'notspam',
    'obligation',
    'offer',
    'once in a lifetime',
    'one time',
    'online marketing',
    'opt in',
    'order now',
    'passwords',
    'pennies a day',
    'pill',
    'please read',
    'potential earnings',
    'pre-approved',
    'prize',
    'psychic healer',
    'pure profit',
    'refinance',
    'requires initial investment',
    'reserves the right',
    'risk-free',
    'sangoma',
    'satisfaction guaranteed',
    'save big money',
    'search engine',
    'see for yourself',
    'sent in compliance',
    'sign up free',
    'skype',
    'social security',
    'south african',
    'special promotion',
    'take action',
    'terms and conditions',
    'thc',
    'unsecured credit',
    'unsecured debt',
    'unsolicited',
    'urgent',
    'usd',
    'valium',
    'viagra',
    'vicodin',
    'wallet',
    'warranty',
    'we hate spam',
    'web traffic',
    'weight loss',
    'what are you waiting for?',
    'whatapp',
    'whatsapp',
    'while supplies last',
    'will not believe your eyes',
    'work from home',
    'xanax',
    'you are a winner',
    'you have been selected',
];
